language: haxe

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - linux
#  - osx

dist: xenial

# Test with Haxe 3.4.7 and Haxe development.
haxe:
  - "4.2.2"
#  - development

neko: "2.3.0"

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # C++ (for rebuilding hxcpp)
      - gcc-multilib
      - g++-multilib
      # Python
      - python3
      # PHP
      - php-cli
      - php-mbstring
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libglib2.0
      - libfreetype6
      # Lua
      - cmake
      - lua5.1
      - luarocks
      - libpcre3-dev
      - libssl-dev

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export DISPLAY=:99.0;
    export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update;
    brew cask uninstall oclint;
    brew cask install phantomjs;
    brew install mono;
    brew upgrade python;
    fi
  # Haxe Lua dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu;
    sudo luarocks install lrexlib-pcre PCRE_LIBDIR=/usr/lib/x86_64-linux-gnu;
    sudo luarocks install luabitop;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew install lua luarocks pcre python;
    sudo luarocks install lrexlib-pcre;
    sudo luarocks install luasocket;
    fi
  - sudo luarocks install luv
  - sudo luarocks install environ
  - sudo luarocks install luautf8
  -
  # Install haxelibs
  - haxelib install munit
  - haxelib git hamcrest https://github.com/mikestead/hamcrest-haxe.git master src --always
  - haxelib git hexinject https://github.com/CrazyFlasher/hexInject.git 73b59e0dccc6f181f3858ff7ee441283345abb1c
  - haxelib install dox
  - haxelib install hxnodejs
script:
  - haxe package.hxml